# Site settings
email: "hackurity01@gmail.com" 
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Hackurity
description: "Hackurity's Blog"
url: "hackurity01.github.io"
twitter_username: 
default_img: 

# Profile settings
name: YuDongKyun
profile_img: 
profile: 
social:
  github: 

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
#markdown: KramdownPygments
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
